version: "3.8"

services:
  front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: web:1
    ports:
      - 80:80 
    restart: unless-stopped
  back:
    build: ./backend
    image: api:1
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    
    command: ./docker-entrypoint.sh
    restart: unless-stopped
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
      
    restart: unless-stopped
volumes:
  vidly: